spring:
  application:
    name: Simple-Rag-App
  ai:
    openai:
      chat:
        base-url: https://api.groq.com/openai/v1
        model: llama-3.3-70b-versatile
        api-key: ${OPENAI_API_KEY}
      embedding:
        base-url: http://localhost:11434/v1
        model: nomic-embed-text

